---
apiVersion: v1
kind: Namespace
metadata:
  name: xkcd-clone

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: xkcd-clone
  name: xkcd-images
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: xkcd-clone
  
  name: xkcd-clone
  labels:
    app: xkcd-clone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xkcd-clone
  template:
    metadata:
      labels:
        app: xkcd-clone
    spec:
      containers:
      - name: xkcd-clone
        image: jlrine2/xkcd
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        volumeMounts:
        - name: archive
          mountPath: /app/static/archive
      volumes:
      - name: archive
        persistentVolumeClaim:
          claimName: xkcd-images

---
apiVersion: v1
kind: Service
metadata:
  namespace: xkcd-clone
  name: xkcd-clone
  labels:
    app: xkcd-clone
spec:
  selector:
    app: xkcd-clone
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
